"-- Basics --"
filetype plugin indent on
syntax on
set showmatch
set nocompatible

if has('termguicolors')
  set termguicolors
endif
colorscheme retrobox
set background=dark

" Line numbers
set number
set relativenumber
set signcolumn=number
set nowrap

" Core behavior
set hidden
set mouse=a
set scrolloff=10

" Indentation
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set smartindent
set backspace=indent,eol,start
set noshowmatch

" Searching
set ignorecase
set smartcase
set hlsearch
set incsearch

"-- Bindings -- "

" Leader Key
let mapleader = " "
let maplocalleader = " "

" Yank to system clipboard
nnoremap <leader>y "+y
vnoremap <leader>y "+y
nnoremap <leader>Y "+Y

" Paste from system clipboard
nnoremap <leader>p "+p
vnoremap <leader>p "+p
nnoremap <leader>P "+P

" Split creation
nnoremap <leader>\ :vsplit<CR>
nnoremap <leader>- :split<CR>

" Buffer management (No Tmux)
nnoremap <leader>w :w<CR>           " Save
nnoremap <leader>q :q<CR>           " Quit
nnoremap <leader>bd :bdelete<CR>    " Buffer delete
nnoremap <S-l> :bnext<CR>           " Next Buffer
nnoremap <S-h> :bprev<CR>           " Prev Buffer

" Visual mode indenting 
vnoremap < <gv
vnoremap > >gv

" Searching and Terminal
nnoremap <Esc> :nohlsearch<CR>
tnoremap <Esc><Esc> <C-\><C-n>

" File Explorer (Netrw)
nnoremap <leader>e :Ex<CR>
nnoremap <leader>l <Plug>NetrwRefresh

" Vim/Tmux Navigation
function! TmuxMove(direction)
    let l:old_win = winnr()
    execute 'wincmd ' . a:direction
    if l:old_win == winnr()
        if !empty($TMUX)
            let l:tmux_dir = {'h': 'L', 'j': 'D', 'k': 'U', 'l': 'R'}[a:direction]
            silent call system('tmux select-pane -' . l:tmux_dir)
        endif
    endif
endfunction

nnoremap <silent> <C-h> :call TmuxMove('h')<CR>
nnoremap <silent> <C-j> :call TmuxMove('j')<CR>
nnoremap <silent> <C-k> :call TmuxMove('k')<CR>
nnoremap <silent> <C-l> :call TmuxMove('l')<CR>
