#!/usr/bin/env zsh

# Version controlled config
export DOTFILES="$HOME/.dotfiles"

# XDG variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/cache"

# Zsh variables
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000

export EDITOR="nvim"
export VISUAL="nvim"


. "$HOME/.cargo/env"
